config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  resources :users, only: [:index, :show] do
    resources :groups, only: [:index, :show, :new, :create, :destroy] do
      resources :expenses, only: [:index, :show, :new, :create, :destroy] do
          resources :expense_groups, only: [:new, :create, :destroy]
       end
    end
  end
  get '/splash', to: 'groups#splash', as: 'splash'

  authenticated :user do
    root 'groups#index', as: :authenticated_root
  end

  unauthenticated do
    get '/', to: redirect('/splash')
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    #
    return unless user.present?

    can :splash, Group
    can :manage, Group
    can :manage, Expense
    can :manage, ExpenseGroup
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/expense.rb
class Expense < ApplicationRecord
  validates :name, presence: true
  validates :amount, presence: true, numericality: { greater_than: 0 }
  belongs_to :author, foreign_key: :author_id, class_name: 'User'
  has_many :expense_groups, dependent: :destroy
  has_many :groups, through: :expense_groups, dependent: :destroy
end

app/models/expense_group.rb
class ExpenseGroup < ApplicationRecord
  belongs_to :expense
  belongs_to :group
end

app/models/group.rb
class Group < ApplicationRecord
  validates :name, presence: true
  belongs_to :author, foreign_key: :author_id, class_name: 'User'
  has_many :expense_groups, dependent: :destroy
  has_many :expenses, through: :expense_groups, dependent: :destroy

  def total_amount_by_group(group_id)
    expenses.joins(:expense_groups).where(expense_groups: { group_id: }).sum('expenses.amount')
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true
  has_many :expenses, foreign_key: :author_id, dependent: :destroy
  has_many :groups, foreign_key: :author_id, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:splash]
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    attributes = %i[name]
    devise_parameter_sanitizer.permit(:sign_up, keys: attributes)
    devise_parameter_sanitizer.permit(:account_update, keys: attributes)
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  def index
    @group = Group.find(params[:group_id])
    @expenses = @group.expenses.order(created_at: :desc)
  end

  def new
    @expense = current_user.expenses.new
    @group = Group.find(params[:group_id])
  end

  def create
    @expense = current_user.expenses.new(expense_params.slice(:name, :amount))
    if @expense.save
      @expense_group = ExpenseGroup.new(expense_id: @expense.id, group_id: params[:expense][:group_id])

      if @expense_group.save
        redirect_to user_group_expenses_path(current_user, params[:expense][:group_id]),
                    notice: 'Expense created successfully'
      end
    else
      render :new
    end
  end

  private

  def expense_params
    params.require(:expense).permit!
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!, except: [:splash]
  # load_and_authorize_resource except: [:splash]
  def index
    @groups = current_user.groups.order(created_at: :desc).includes(:expenses)
  end

  def new
    @group = current_user.groups.new
  end

  def create
    if params[:group][:picture].present?
      uploaded_file = params[:group][:picture].tempfile
      cloudinary_response = Cloudinary::Uploader.upload(uploaded_file.path, folder: 'group_icons')
      @group = current_user.groups.new(group_params.merge(icon: cloudinary_response['secure_url']).except(:picture))
    else
      @group = current_user.groups.new(group_params.except(:picture))
    end
    if @group.save
      redirect_to authenticated_root_path, notice: 'Categories created successfully'
    else
      render :new
    end
  end

  def splash; end

  private

  def group_params
    params.require(:group).permit(:name, :picture)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    if params[:id] == 'sign_out'
      sign_out_and_redirect
    else
      find_user
    end
  end

  private

  def sign_out_and_redirect
    sign_out current_user
    redirect_to splash_path
  end

  def find_user
    @user = User.find_by(id: params[:id])
    redirect_to users_path, alert: 'User not found' unless @user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/expenses/_form.html.erb
<%= form_with model: [current_user, @group, Expense.new], url: user_group_expenses_path(current_user, @group) do |form| %>
  <div class="sign_in_holder">
    <div class="sign_in_fields">
      <%= form.text_field :name, placeholder: 'Name', required: true %>
      <%= form.number_field :amount, step: :any, required: true, placeholder: 'Amount' %>
      <%= form.collection_select :group_id, @current_user.groups, :id, :name, { prompt: 'Select a group' }, required: true %>
    </div>
    <div>
      <%= form.submit 'Save' %>
    </div>
  </div>
<% end %>

app/views/expenses/index.html.erb
<div class="group_holder">
  <div class="group_card">
    <div class="card_element">
      <div class="picture_holder">
        <img src=<%= @group.icon %> alt="group picture">
      </div>
      <div class="name_holder">
        <h5 class="group_name">
          <%=@group.name%>
        </h5>
        <p class="detail_description">A financial transaction is an agreement, or communication, between a buyer and seller to exchange goods, services, or assets for payment.</p>
      </div>
    </div>
    <hr>
    <div>
      <% @expenses.each do |expense| %>
        <div class="transaction">
          <p>Transaction No <%=expense.id%></p>
          <div class="transaction_detail">
            <p><%=expense.created_at.strftime('%d %B %Y')%></p>
            <p>$<%=expense.amount%></p>
          </div>
        </div>
      <% end %>
    </div>
    <hr>
    <div class="total_transaction">
      <h5 class="total_font">TOTAL PAYMENT</h5>
      <h5 class="total_font">$<%=number_with_delimiter(@group.total_amount_by_group(@group.id))%></h5>
    </div>
  </div>
</div>
<div>
  <button class="button_holder"><%= link_to "Add a new transaction", new_user_group_expense_path(current_user,@group), class: "button_text" %></button>
</div>
</div>

app/views/expenses/new.html.erb
<%= render 'form', expense:@expense %>

app/views/groups/_form.html.erb
<%= form_with(model: [current_user, current_user.groups.build], multipart: true) do |form| %>
  <div class="sign_in_holder">
    <div class="sign_in_fields">
      <div>
        <%= form.text_field :name , placeholder:'Name', required: true %>
      </div>
      <div class="picture_input">
        <p class="custom-file-label" >Choose icon</p>
        <%= form.file_field :picture, class: "file-input", id: "file-input", required: true %>
      </div>
    </div>
    <div>
      <%= form.submit "Save"%>
    </div>
  </div>
<% end %>

app/views/groups/index.html.erb
<div class="group_holder">
  <% @groups.each do |group| %>
    <div class="group_card">
      <div class="card_element">
        <div class="picture_holder">
          <img src=<%= group.icon %> alt="group picture">
        </div>
        <div class="group_description_holder">
          <div class="name_total_holder">
            <h5 >
              <%= link_to "#{group.name}", user_group_expenses_path(current_user,group.id), class:"group_name"%>
            </h5>
            <h5 class="group_amount">$<%=group.total_amount_by_group(group.id)%></h5>
          </div>
          <div class="group_date_holder">
            <hr>
            <p class="group_date_created">
              <p class="group_date_created">
                <%= group.created_at.strftime('%d %B %Y') %>
              </p>
            </p>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <div>
    <button class="button_holder" ><%= link_to "Add a new category", new_user_group_path(current_user), class:"button_text" %></button>
  </div>
</div>

app/views/groups/new.html.erb
<%= render 'form', group:@group%>

app/views/groups/splash.html.erb
<div class="splash_holder">
  <h2 class=" green-grey-text" ><i>My Budget</i> <br>
    <i>APPLICATION </i>
    <br><i>BY: </i>
    <br><i>Felix Sowah </i></h2>
  <div class="splash_button_holder">
    <button class="waves-effect btn-large light-blue darken-3 btn-flat">
      <%= link_to "Sign In", new_user_session_path, class:'white-text'  %>
    </button>
    <button class="waves-effect btn-large white btn-flat" >
      <%= link_to  "Sign Up", new_user_registration_path, class:' blue-grey-text ' %>
    </button class="">
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <link href="https://fonts.cdnfonts.com/css/proxima-nova-2" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <%= javascript_importmap_tags %>
  </head>
  <body class="#eceff1 blue-grey lighten-4 center-align">
    <main class="col s12 m6  blue-grey lighten-5 ">
      <% unless current_page?(splash_path) && current_user.nil? %>
        <%= render 'shared/navbar' %>
      <% end %>
      <%=render 'shared/flash'%>
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_flash.html.erb
<div class="notification">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
</div>

app/views/shared/_navbar.html.erb
<div class="nav_bar">
  <% if current_page?(new_user_session_path) || request&.path&.include?('/users/sign_in')%>
    <div ><%= link_to(:back) do %>
        <%= content_tag(:div) do %>
          <i class="material-icons white-text">arrow_back</i>
        <% end %>
      <% end %></div>
    <h5>LOGIN</h5>
    <p>Log in</p>
  <% end %>
  <% if current_page?(new_user_registration_path) || request&.path == '/users' %>
    <div ><%= link_to(:back) do %>
        <%= content_tag(:div) do %>
          <i class="material-icons white-text">arrow_back</i>
        <% end %>
      <% end %></div>
    <h5>REGISTER</h5>
    <p>Next</p>
  <% end %>
  <% if current_page?(new_user_password_path) || request&.path&.include?('/users/password') %>
    <div ><%= link_to(:back) do %>
        <%= content_tag(:div) do %>
          <i class="material-icons white-text">arrow_back</i>
        <% end %>
      <% end %></div>
    <h5>RESET PASSWORD</h5>
    <p>Reset</p>
  <% end %>

  <% if current_page?(authenticated_root_path) && !current_user.nil?  %>
    <div>
      <i class="material-icons white-text">menu</i>
    </div>
    <h5>TRANSACTIONS</h5>
    <h6><%= link_to "Sign out", destroy_user_session_path, class:"white-text" %></h6>  <% end %>
  <% if request&.path&.include?('groups/new')%>
    <%if current_page?(new_user_group_path(current_user))%>
      <div ><%= link_to authenticated_root_path do %>
          <%= content_tag(:div) do %>
            <i class="material-icons white-text">arrow_back</i>
          <% end %>
        <% end %></div>
      <h5>CREATE NEW CATEGORY</h5>
      <p>Create</p>
    <% end %>
  <% end %>
  <% if request&.path&.include?('expenses') %>
    <% if request.path ==user_group_expenses_path(current_user, @group)%>
      <div>
        <%= link_to authenticated_root_path do %>
          <%= content_tag(:div) do %>
            <i class="material-icons white-text">arrow_back</i>
          <% end %>
        <% end %>
      </div>
      <h5>DETAILS</h5>
      <p></p>
    <% end %>
  <% end %>
  <% if request&.path&.include?('expenses/new') %>
    <%if current_page?(new_user_group_expense_path(current_user, @group))%>
      <div ><%= link_to(:back) do %>
          <%= content_tag(:div) do %>
            <i class="material-icons white-text">arrow_back</i>
          <% end %>
        <% end %></div>
      <h5>ADD NEW TRANSACTIONS </h5>
      <p>Create</p>
    <% end %>
  <% end %>
</div>